### ISSUE TITLE
Application blocked by java

### ISSUE THREAD

**Issue by sophiekruijt** [e-Contract/eid-applet#5]
I followed exactly all the steps that are provided in the documentation and uploaded the final .war file to a server at openshift.com. But no matter what I try, and even when I add the url as an exception in the java security settings I still get this error.

Do you have any idea what I should change to get it running?
https://mijnzorgtraject-stefankruijt.rhcloud.com/eid-applet/

**Comment by ThijsWouters** [comment]
I got the following exception:

```
Exception was: 
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize applet. For more information click "more information button".
    at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:739)
    at net.sourceforge.jnlp.Launcher.getApplet(Launcher.java:668)
    at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:901)
Caused by: net.sourceforge.jnlp.LaunchException: Signed applets are not allowed to run when their actual Codebase does not match the Codebase specified in their manifest. Expected: https://*.be https://*.brussels https://*.vlaanderen localhost 127.0.0.1 . Actual: https://mijnzorgtraject-stefankruijt.rhcloud.com/eid-applet/. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
    at net.sourceforge.jnlp.runtime.ManifestAttributesChecker.checkCodebaseAttribute(ManifestAttributesChecker.java:168)
    at net.sourceforge.jnlp.runtime.ManifestAttributesChecker.checkAll(ManifestAttributesChecker.java:80)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader. (JNLPClassLoader.java:288)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:351)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:418)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:394)
    at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:704)
    ... 2 more
```

Line 6 says it all: you can only run the eid applet on domains with tld `.be`, `.brussels`, `.vlaanderen`.

**Comment by fcorneli** [comment]
We only support BE domains. Please use the eID Identity Provider if you want to service a .com domain.

**Comment by sophiekruijt** [comment]
I would love using the eID Identity provider, but since I'm Dutch I don't have a Belgium eID card. I do have a test card, but that card generates an error with the eID Identity Provider. Isn't there a way to make it possible to use the test eID card for the eID Identity provider?
Since I think it's really hard to develop an application without being able to test whether things work myself.

**Comment by fcorneli** [comment]
Today we've setup a test eID Identity Provider. This test eID Identity Provider can also handle test eID cards. If interested, drop us an email at info@e-contract.be.

**Comment by sophiekruijt** [comment]
That's really a nice improvement! :+1:
